version: "3.8"

services:
  inventory-postgres:
    container_name: inventory-postgres
    image: postgres
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
