name: Coverage

on:
  workflow_call:
  pull_request:

permissions:
  contents: read

jobs:
  tarpaulin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-tarpaulin

      - name: Generate coverage
        run: >-
          cargo tarpaulin
          --workspace
          --timeout 300
          --out Lcov
